Q1. SImple Maths Quiz Auto Generator (40%)

In [41]:
#Write a program that generates simple additions quizzes. The program should first display two random numbers to be added, and invite user to enter an answer. If the answer is correct, a message of congratulations should be displayed. Otherwise, a message showing the correct answer should be displayed.

import random

def math_quiz():
    num1 = random.randint(1,500)
    num2 = random.randint(1,500)
    print(f"  {num1}\n+ {num2}")
    answer = int(input("Enter sum of numbers: "))
    if answer == num1 + num2:
        print("Correct answer - Good job!")
    else:
        print(f"Incorrect! The correct answer is: {num1 + num2} ")

math_quiz()

  460
+ 181
Enter sum of numbers: 641
Correct answer - Good job!

Q2. Data Preparation and Wrangling

In [28]:
#1. Importing the dataset
#a. Load the Housing Dataset using Pandas
import pandas as pd
Housing_data= pd.read_csv('https://raw.githubusercontent.com/Dong2Yo/PredcitiveAnalysis_BusinessProfessional/main/data/housing.csv')

In [29]:
#b. Display the first 5 rows of the dataset
Housing_data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [30]:
#2. Data Exploration
#a. Check the structure of the dataset, including column names, data types, and missing values
Housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [31]:
#3. Basic DataFrame Operations
#a. Calculate summary statistics (mean, median, min, max) for the column of "total_rooms".
Housing_data['total_rooms'].describe()

count    20640.000000
mean      2635.763081
std       2181.615252
min          2.000000
25%       1447.750000
50%       2127.000000
75%       3148.000000
max      39320.000000
Name: total_rooms, dtype: float64

In [32]:
#b. Count the number of unique values in the column of "ocean_proximity".
Housing_data['ocean_proximity'].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [33]:
#4. Data Cleaning
#a. Check for missing values in the dataset and count the number of missing values in each column
Housing_data.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [34]:
#b. Replace missing values with the mean of that column
Housing_data['total_bedrooms'].fillna(df['total_bedrooms'].mean(), inplace=True)

In [35]:
#c. Display the number of missing values of that column
Housing_data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [36]:
#5. Data Wrangling
#a. Add a new column to the dataset, which calculates the "price per room" by dividing the "median_house_value" by the "total_rooms".
Housing_data['price_per_room'] = Housing_data['median_house_value'] / Housing_data['total_rooms']

In [37]:
#b. Show the last 5 records of the new column of "price per room".
Housing_data['price_per_room'].tail()

20635     46.906907
20636    110.616930
20637     40.949423
20638     45.537634
20639     32.100539
Name: price_per_room, dtype: float64

In [38]:
#c. Filter the dataset to select only the rows where the "median_income" is greater than 5 and the "ocean_proximity" is "NEAR BAY."
Housing_data[(Housing_data['median_income'] > 5) & (Housing_data['ocean_proximity'] == 'NEAR BAY')]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,price_per_room
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,514.318182
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,50.500070
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,240.013633
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,267.896389
61,-122.29,37.82,49.0,135.0,29.0,86.0,23.0,6.1183,75000.0,NEAR BAY,555.555556
...,...,...,...,...,...,...,...,...,...,...,...
18935,-122.18,38.23,21.0,2475.0,341.0,812.0,308.0,7.2589,320400.0,NEAR BAY,129.454545
18936,-122.14,38.16,4.0,3273.0,495.0,1497.0,454.0,5.3345,176100.0,NEAR BAY,53.803850
18937,-122.18,38.17,7.0,4093.0,651.0,2228.0,646.0,5.2523,161300.0,NEAR BAY,39.408747
18939,-122.10,38.24,13.0,7367.0,1042.0,3193.0,983.0,5.3102,195000.0,NEAR BAY,26.469391
19067,-122.45,38.28,20.0,3306.0,503.0,1374.0,460.0,5.7984,297600.0,NEAR BAY,90.018149

In [39]:
#d. Export filtered dataset to CSV with the name of "filtered_housing_FirstLastName".
Housing_data[(Housing_data['median_income'] > 5) & (Housing_data['ocean_proximity'] == 'NEAR BAY')].to_csv('filtered_housing_AmandaCruz.csv', index=False)